"""add api_calls table

Revision ID: 6885c63894c3
Revises: 96d6d97b1ee6
Create Date: 2026-10-04 01:00:26.851448

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6885c63894c3'
down_revision: Union[str, Sequence[str], None] = '96d6d97b1ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_calls_resource_ts', 'api_calls', ['resource', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_calls_resource_ts', table_name='api_calls')
    op.drop_table('api_calls')
    # ### end Alembic commands ###
